# Generated by Django 5.1.7 on 2025-03-15 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaqueue', '0002_track_genre_track_import_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
