# Generated by Django 5.1.7 on 2025-03-15 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediaqueue', '0003_track_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='external_link',
            new_name='external_links',
        ),
    ]
