# Generated by Django 5.1.7 on 2025-03-15 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaqueue', '0004_rename_external_link_track_external_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='alias',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
